/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Workspace\Projects\Sars\public\assets\player.glb -o D:\Workspace\Projects\Sars\PlayerModelInfo.tsx 
Author: iJUNE (https://sketchfab.com/iJUNE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-player-a84dac68352242f1abd258ba9c46bd7e
Title: [ FREE ] Player
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'idle' | 'walk' | 'run' | 'punch'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_91: THREE.Mesh
    Object_94: THREE.Mesh
    Object_98: THREE.Mesh
    Object_101: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
    Object_41: THREE.Mesh
    Object_43: THREE.Mesh
    Object_45: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_51: THREE.Mesh
    Object_53: THREE.Mesh
    Object_55: THREE.Mesh
    Object_57: THREE.Mesh
    Object_59: THREE.Mesh
    Object_61: THREE.Mesh
    Object_63: THREE.Mesh
    Object_65: THREE.Mesh
    Object_67: THREE.Mesh
    Object_69: THREE.Mesh
    Object_71: THREE.Mesh
    Object_73: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_79: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_120: THREE.Mesh
    Object_117: THREE.Mesh
    Object_126: THREE.Mesh
    Object_123: THREE.Mesh
    Object_134: THREE.Mesh
    Object_129: THREE.Mesh
    Object_131: THREE.Mesh
    Object_140: THREE.Mesh
    Object_137: THREE.Mesh
    Object_146: THREE.Mesh
    Object_143: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_107: THREE.Mesh
    Object_109: THREE.Mesh
    Object_104: THREE.Mesh
    Object_167: THREE.Mesh
    Object_164: THREE.Mesh
    Object_175: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_181: THREE.Mesh
    Object_178: THREE.Mesh
    Object_187: THREE.Mesh
    Object_184: THREE.Mesh
    Object_193: THREE.Mesh
    Object_190: THREE.Mesh
    Object_159: THREE.Mesh
    Object_161: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_149: THREE.Mesh
    Object_13: THREE.Mesh
    Object_10: THREE.Mesh
    Object_205: THREE.Mesh
    Object_207: THREE.Mesh
    Object_209: THREE.Mesh
    Object_211: THREE.Mesh
    Object_213: THREE.Mesh
    Object_215: THREE.Mesh
    Object_202: THREE.Mesh
    Object_199: THREE.Mesh
    Object_224: THREE.Mesh
    Object_226: THREE.Mesh
    Object_228: THREE.Mesh
    Object_230: THREE.Mesh
    Object_232: THREE.Mesh
    Object_234: THREE.Mesh
    Object_221: THREE.Mesh
    Object_218: THREE.Mesh
    Object_196: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    material_1: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: any) {
  const group = React.useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/player.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_138">
                <group name="All_137" position={[0, 0.063, 0]}>
                  <group name="Chest1_112" position={[0, 0.953, 0]}>
                    <group name="Chest2_111" position={[0, 0.2, 0]}>
                      <group name="Head_51" position={[0, 0.425, 0]}>
                        <group name="BB_45">
                          <group name="Brow2_42" position={[0.049, 0.168, -0.173]}>
                            <group name="cube_41" position={[0.031, 0, 0]}>
                              <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="Brow_44" position={[-0.049, 0.168, -0.173]}>
                            <group name="cube_43" position={[-0.031, 0, 0]}>
                              <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_1} />
                            </group>
                          </group>
                        </group>
                        <group name="EE_50" position={[0, 0.162, -0.169]}>
                          <group name="E1_47" position={[0.077, 0.009, -0.006]}>
                            <group name="cube_46">
                              <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="E2_49" position={[-0.077, 0.009, -0.006]}>
                            <group name="cube_48">
                              <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.material_1} />
                            </group>
                          </group>
                        </group>
                        <group name="cube_4" position={[0, 0.141, 0]}>
                          <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_5" position={[-0.185, 0.083, -0.027]} rotation={[0, -Math.PI / 8, 0]}>
                          <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_6" position={[-0.18, 0.039, -0.038]} rotation={[0, -Math.PI / 8, 0]}>
                          <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_7" position={[0.185, 0.083, -0.027]} rotation={[0, Math.PI / 8, 0]}>
                          <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_8" position={[0.18, 0.039, -0.038]} rotation={[0, Math.PI / 8, 0]}>
                          <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_9" position={[0, 0.1, -0.169]} rotation={[Math.PI / 8, 0, 0]}>
                          <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_1} />
                        </group>
                        <group name="cube_10" position={[0, 0.1, -0.169]} rotation={[Math.PI / 8, 0, 0]}>
                          <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_1} />
                        </group>
                        <group name="Hair_40" position={[1.063, 0.236, -0.055]}>
                          <group name="cube_11" position={[-1.105, 0.05, 0.047]} rotation={[0, 0, -Math.PI / 8]}>
                            <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_12" position={[-1.169, 0.068, 0.047]}>
                            <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_13" position={[-1.201, 0.063, 0.047]} rotation={[0, 0, Math.PI / 8]}>
                            <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_14" position={[-1.221, 0.05, 0.047]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_15" position={[-1.231, 0.003, 0.047]}>
                            <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_16" position={[-1.165, 0.023, -0.144]} rotation={[-Math.PI / 4, 0, 0]}>
                            <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_17" position={[-1.165, -0.027, -0.165]}>
                            <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_18" position={[-1.222, -0.065, -0.14]} rotation={[0, Math.PI / 8, 0]}>
                            <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_19" position={[-1.235, -0.071, -0.089]}>
                            <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_20" position={[-1.235, -0.072, -0.011]} rotation={[Math.PI / 4, 0, 0]}>
                            <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_21" position={[-1.169, -0.067, -0.164]} rotation={[0, 0, Math.PI / 8]}>
                            <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_22" position={[-1.02, 0.05, 0.047]} rotation={[0, 0, Math.PI / 8]}>
                            <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_23" position={[-0.956, 0.068, 0.047]}>
                            <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_24" position={[-0.924, 0.063, 0.047]} rotation={[0, 0, -Math.PI / 8]}>
                            <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_25" position={[-0.904, 0.05, 0.047]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_26" position={[-0.894, 0.003, 0.047]}>
                            <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_27" position={[-0.89, -0.072, -0.011]} rotation={[Math.PI / 4, 0, 0]}>
                            <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_28" position={[-0.89, -0.071, -0.089]}>
                            <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_29" position={[-0.904, -0.065, -0.14]} rotation={[0, -Math.PI / 8, 0]}>
                            <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_30" position={[-0.956, -0.067, -0.164]} rotation={[0, 0, -Math.PI / 8]}>
                            <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_31" position={[-0.961, -0.027, -0.165]}>
                            <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_32" position={[-0.961, 0.023, -0.144]} rotation={[-Math.PI / 4, 0, 0]}>
                            <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_33" position={[-1.132, -0.001, -0.12]} rotation={[0, 0, Math.PI / 8]}>
                            <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_34" position={[-0.993, -0.001, -0.12]} rotation={[0, 0, -Math.PI / 8]}>
                            <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_35" position={[-1.061, 0.025, 0.235]} rotation={[Math.PI / 4, 0, 0]}>
                            <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_36" position={[-1.061, -0.03, 0.243]}>
                            <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_37" position={[-1.17, -0.083, 0.238]} rotation={[0, 0, -Math.PI / 4]}>
                            <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_38" position={[-0.955, -0.083, 0.238]} rotation={[0, 0, Math.PI / 4]}>
                            <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_39" position={[-1.062, -0.098, 0.238]}>
                            <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.material_1} />
                          </group>
                        </group>
                      </group>
                      <group name="Arm_80" position={[-0.227, 0.359, 0.016]}>
                        <group name="Arm2_79" position={[-0.078, -0.3, 0]}>
                          <group name="Hand_78" position={[-0.003, -0.349, 0]}>
                            <group name="F9_60" position={[0.005, -0.096, -0.112]}>
                              <group name="F10_59" position={[0, -0.066, 0]}>
                                <group name="cube_58" position={[0.013, -0.031, 0]}>
                                  <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_57" position={[0.013, -0.031, 0]}>
                                <mesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F1_64" position={[-0.039, -0.14, -0.063]}>
                              <group name="F2_63" position={[0, -0.066, 0]}>
                                <group name="cube_62" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_61" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_123" geometry={nodes.Object_123.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F3_69" position={[-0.039, -0.14, -0.013]}>
                              <group name="F4_68" position={[0, -0.066, 0]}>
                                <group name="cube_67" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_65" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_129" geometry={nodes.Object_129.geometry} material={materials.material_1} />
                              </group>
                              <group name="cube_66" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_131" geometry={nodes.Object_131.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F5_73" position={[-0.039, -0.14, 0.038]}>
                              <group name="F6_72" position={[0, -0.066, 0]}>
                                <group name="cube_71" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_70" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_137" geometry={nodes.Object_137.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F7_77" position={[-0.039, -0.14, 0.087]}>
                              <group name="F8_76" position={[0, -0.066, 0]}>
                                <group name="cube_75" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_74" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_143" geometry={nodes.Object_143.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="cube_55" position={[0.003, -0.015, 0]}>
                              <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_1} />
                            </group>
                            <group name="cube_56" position={[-0.016, -0.085, 0]}>
                              <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="cube_53" position={[0, -0.169, 0]}>
                            <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_54" position={[0, -0.169, 0]}>
                            <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.material_1} />
                          </group>
                        </group>
                        <group name="cube_52" position={[-0.078, -0.125, 0]}>
                          <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_1} />
                        </group>
                      </group>
                      <group name="Arm3_110" position={[0.227, 0.359, 0.016]}>
                        <group name="Arm4_109" position={[0.078, -0.3, 0]}>
                          <group name="Hand2_108" position={[0.003, -0.349, 0]}>
                            <group name="F11_90" position={[-0.005, -0.096, -0.112]}>
                              <group name="F12_89" position={[0, -0.066, 0]}>
                                <group name="cube_88" position={[-0.013, -0.031, 0]}>
                                  <mesh name="Object_167" geometry={nodes.Object_167.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_87" position={[-0.013, -0.031, 0]}>
                                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F13_95" position={[0.039, -0.14, -0.063]}>
                              <group name="F14_94" position={[0, -0.066, 0]}>
                                <group name="cube_93" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_91" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.material_1} />
                              </group>
                              <group name="cube_92" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F15_99" position={[0.039, -0.14, -0.013]}>
                              <group name="F16_98" position={[0, -0.066, 0]}>
                                <group name="cube_97" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_181" geometry={nodes.Object_181.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_96" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F17_103" position={[0.039, -0.14, 0.038]}>
                              <group name="F18_102" position={[0, -0.066, 0]}>
                                <group name="cube_101" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_187" geometry={nodes.Object_187.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_100" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="F19_107" position={[0.039, -0.14, 0.087]}>
                              <group name="F20_106" position={[0, -0.066, 0]}>
                                <group name="cube_105" position={[0, -0.031, -0.013]}>
                                  <mesh name="Object_193" geometry={nodes.Object_193.geometry} material={materials.material_1} />
                                </group>
                              </group>
                              <group name="cube_104" position={[0, -0.031, -0.013]}>
                                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.material_1} />
                              </group>
                            </group>
                            <group name="cube_85" position={[-0.003, -0.015, 0]}>
                              <mesh name="Object_159" geometry={nodes.Object_159.geometry} material={materials.material_1} />
                            </group>
                            <group name="cube_86" position={[0.016, -0.085, 0]}>
                              <mesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.material_1} />
                            </group>
                          </group>
                          <group name="cube_82" position={[0, -0.169, 0]}>
                            <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_83" position={[0, -0.169, 0]}>
                            <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_84" position={[0, -0.169, 0]}>
                            <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material_1} />
                          </group>
                        </group>
                        <group name="cube_81" position={[0.078, -0.125, 0]}>
                          <mesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.material_1} />
                        </group>
                      </group>
                      <group name="cube_3" position={[0, 0.206, 0]}>
                        <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.material_1} />
                      </group>
                    </group>
                    <group name="cube_2" position={[0, 0.109, 0]}>
                      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_1} />
                    </group>
                  </group>
                  <group name="Bot_136" position={[0, 0.914, 0]}>
                    <group name="Leg1_124" position={[-0.111, -0.034, 0]}>
                      <group name="Leg2_123" position={[0, -0.425, 0]}>
                        <group name="Foot_122" position={[0, -0.406, 0.005]}>
                          <group name="cube_116" position={[0, -0.086, -0.034]}>
                            <mesh name="Object_205" geometry={nodes.Object_205.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_117" position={[0, -0.104, -0.177]} rotation={[-Math.PI / 4, 0, 0]}>
                            <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_118" position={[0, -0.074, -0.155]}>
                            <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_119" position={[0, -0.049, -0.15]} rotation={[-Math.PI / 8, 0, 0]}>
                            <mesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_120" position={[0, -0.031, -0.007]}>
                            <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_121" position={[0, 0.006, -0.008]}>
                            <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.material_1} />
                          </group>
                        </group>
                        <group name="cube_115" position={[0, -0.181, 0]}>
                          <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.material_1} />
                        </group>
                      </group>
                      <group name="cube_114" position={[0, -0.2, 0]}>
                        <mesh name="Object_199" geometry={nodes.Object_199.geometry} material={materials.material_1} />
                      </group>
                    </group>
                    <group name="Leg3_135" position={[0.111, -0.034, 0]}>
                      <group name="Leg4_134" position={[0, -0.425, 0]}>
                        <group name="Foot2_133" position={[0, -0.406, 0.005]}>
                          <group name="cube_127" position={[0, -0.086, -0.034]}>
                            <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_128" position={[0, -0.031, -0.007]}>
                            <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_129" position={[0, 0.006, -0.008]}>
                            <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_130" position={[0, -0.104, -0.177]} rotation={[-Math.PI / 4, 0, 0]}>
                            <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_131" position={[0, -0.074, -0.155]}>
                            <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.material_1} />
                          </group>
                          <group name="cube_132" position={[0, -0.049, -0.15]} rotation={[-Math.PI / 8, 0, 0]}>
                            <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.material_1} />
                          </group>
                        </group>
                        <group name="cube_126" position={[0, -0.181, 0]}>
                          <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.material_1} />
                        </group>
                      </group>
                      <group name="cube_125" position={[0, -0.2, 0]}>
                        <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.material_1} />
                      </group>
                    </group>
                    <group name="cube_113">
                      <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.material_1} />
                    </group>
                  </group>
                </group>
                <group name="hitbox_1">
                  <group name="cube_0">
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/player.glb')
